name: Baicaiba

on:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./白菜/白菜.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./白菜/Baicaiba.py 
        env:
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}
            DJJ_TELE_COOKIE: ${{ secrets.DJJ_TELE_COOKIE }}
            bd_tb_url: ${{ secrets.bd_tb_url }}
            bd_tb_bd: ${{ secrets.bd_tb_bd }}
            bd_tb_hd: ${{ secrets.bd_tb_hd }}
            bd_tb_ck: ${{ secrets.bd_tb_ck }}
            bd_tb_task: ${{ secrets.bd_tb_task }}
