name: 测试同步
  
on:
    # push:
    #     branches:
    #         - main
  schedule:
     - cron: "10 16 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Github进行fork后如何与原仓库同步
       run: |
           git remote add upstream git https://github.com/canghaiyishengxiao2021/dadonggua.git
           git remote -v
           git fetch upstream
           git checkout main
           git merge upstream/main
           #git pull origin main --allow-unrelated-histories
           git push origin main
